easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Ingredient
        - App\Entity\User
        - App\Entity\Recipe
        - App\Entity\ImageFile
        - App\Entity\Comment
        - App\Entity\RefUnit
        - App\Entity\IngredientDisplayPreferenceOverride
