twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    paths:
        '%kernel.project_dir%/templates': templates
        '%kernel.project_dir%/vendor/brokoskokoli/star-rating-bundle/Resources/views': BrokoskokoliStarRatingBundle