# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        route: security_index
        _locale: '%locale%'

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /easyadmin
